# Generated by Django 5.0.1 on 2024-01-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_campaign_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.AddField(
            model_name='campaign',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
