# Generated by Django 5.0.1 on 2024-01-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='sizes',
        ),
    ]
